import "../styles/tailwind.css"

import type { Metadata } from "next"
import type { ReactNode } from "react"

import ClientThemeProvider from "@/components/ClientThemeProvider"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"
import { Roboto } from "next/font/google"

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    display: "swap",
    variable: "--font-roboto",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: ReactNode
}>) {
    return (
        <html lang="en">
            <body className={roboto.variable}>
                <AppRouterCacheProvider>
                    <ClientThemeProvider>
                        {children}
                    </ClientThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    )
}
